In [18]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
import ast
import joblib
import os

In [19]:
df = pd.read_csv('C:/Users/User/Desktop/fallexcel/combined_Subject_4.csv') 
df = df.drop(df.columns[0], axis=1)
df.head()

,"x1, y1, confidence1","x2, y2, confidence2","x3, y3, confidence3","x4, y4, confidence4","x5, y5, confidence5","x6, y6, confidence6","x7, y7, confidence7","x8, y8, confidence8","x9, y9, confidence9","x10, y10, confidence10","x11, y11, confidence11","x12, y12, confidence12","x13, y13, confidence13","x14, y14, confidence14","x15, y15, confidence15","x16, y16, confidence16","x17, y17, confidence17",label
0,"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.23288156, 0.2911118)","(0.0, 0.0)","(0.24753892, 0.36143857)","(0.3117138, 0.30932587)","(0.24587075, 0.47934428)","(0.35076293, 0.38649213)","(0.24767834, 0.54722655)","(0.32998475, 0.46833184)","(0.31367058, 0.52798575)","(0.35650727, 0.506506)","(0.3269688, 0.64723396)","(0.35961604, 0.5984466)","(0.35690913, 0.7497779)","(0.39563903, 0.694425)",0
1,"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.23467308, 0.28417584)","(0.0, 0.0)","(0.24413489, 0.36059743)","(0.31360182, 0.31231153)","(0.24139076, 0.47751966)","(0.35363692, 0.39086294)","(0.24895649, 0.5461843)","(0.3316386, 0.4680968)","(0.3109158, 0.52639186)","(0.3571222, 0.5067806)","(0.3261711, 0.6449606)","(0.3618758, 0.5983182)","(0.3546629, 0.7499989)","(0.40177003, 0.697664)",0
2,"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.23559399, 0.28077325)","(0.0, 0.0)","(0.24650063, 0.36624926)","(0.31982028, 0.31878835)","(0.23719668, 0.48641104)","(0.3552843, 0.39376953)","(0.24637127, 0.5429314)","(0.34398025, 0.4642221)","(0.30947235, 0.5345761)","(0.3570922, 0.5135805)","(0.3255149, 0.64766526)","(0.37188202, 0.5974459)","(0.35807607, 0.74749166)","(0.40616524, 0.69086957)",0
3,"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.24238992, 0.27923238)","(0.0, 0.0)","(0.24988627, 0.36803994)","(0.3234948, 0.32046285)","(0.23849037, 0.48632854)","(0.35764727, 0.39468262)","(0.2541622, 0.52852756)","(0.350829, 0.4690185)","(0.30556127, 0.533619)","(0.35453862, 0.5129034)","(0.32900426, 0.6455195)","(0.38081062, 0.5926929)","(0.36026073, 0.7440988)","(0.41388404, 0.68455416)",0
4,"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.25602853, 0.2679854)","(0.2877817, 0.25337276)","(0.25331515, 0.3592337)","(0.32446602, 0.3229645)","(0.24091725, 0.47102875)","(0.36831602, 0.41178694)","(0.2662041, 0.49228626)","(0.36025387, 0.47070533)","(0.30754852, 0.5231247)","(0.35567746, 0.51221484)","(0.33447185, 0.64138854)","(0.37677333, 0.60878086)","(0.37448934, 0.7398968)","(0.41638628, 0.704132)",0

In [26]:
def convert_string_tuple_to_floats(s):
    if isinstance(s, str):
        return np.array(ast.literal_eval(s), dtype=np.float64)
    else:
        return s
# Apply the conversion to all relevant columns
for column in df.columns[:-1]:  # Assuming the last column is the target
    df[column] = df[column].apply(convert_string_tuple_to_floats)

# # Display the first few rows to check the conversion
# print(df.head())

# Prepare the data for the k-NN model
X = np.array([np.hstack(row) for row in df.iloc[:,:-1].values])  # Flatten the arrays into a 2D array
y = df.iloc[:,-1].values
# print(X[0])
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (mean=0, variance=1)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X_train[0])

[-1.36775097 -1.12977468 -1.18182512 -0.95730664 -0.78107983 -0.65738152
  0.61839912  0.67616329 -0.67384912 -0.53995666 -0.19981864  0.3317208
  0.28231617 -0.01566388 -0.35687216  0.58632725  0.73114627 -0.14132722
 -0.32701567  0.77878345  0.74942756 -0.51040254 -0.17725883  0.45724495
  0.346666    0.31367757 -7.06731762 -4.97807704 -6.5350024  -4.86293733
 -5.80442588 -4.7577902  -3.91965525 -3.52729211]

In [10]:
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Display the predictions and the actual labels
print("\nPredictions:", y_pred)
print("Actual labels:", y_test)

Accuracy: 0.98

Predictions: [2 0 1 2 0 2 2 0 0 0 0 0 1 0 1 1 0 1 2 1 2 0 2 1 1 0 0 1 0 2 0 2 0 2 0 1 0
 0 0 1 1 1 0 0 1 0 2 0 0 2 2 2 1 2 0 2 2 2 2 0 1 2 2 0 0 0 2 2 0 1 1 2 0 1
 2 0 0 1 0 1 1 1 0 1 2 1 0 0 0 2 1 1 2 0 2 2 2 2 1 1 1 2 1 0 0 0 0 0 1 0 0
 1 0 0 1 0 2 2 0 2 0 0 0 0 1 1 1 0 2 1 1 0 2 0 2 0 2 2 2 1 1 2 2 2 2 0 2 0
 0 2 0 2 0 1 2 0 2 0 2 1 2 2 2 1 0 0 0 1 0 1 1 1 0 0 2 0 1 1 2 1 2 2 1 0 0
 0 2 0 1 0 0 0 1 0 2 0 0 0 2 0 0 1 0 0 1 0 0 2 1 0 0 0 1 0 2 0 0 0 2 0 1 2
 0 1 1 0 0 0 2 1 2 1 2 1 2 0 1 0 2 0 0 1 2 0 1 1 0 2 0 0 1 0 2 0 2 2 2 0 2
 0 0 0 0 0 2 2 0 0 0 1 1 1 0 0 2 0 2 0 0 2 2 2 0 0 2 2 2 0 0 1 2 0 2 0 0 2
 1 0 2 0 1 1 1 2 2 1 0 0 0 2 0 1 0 2 2 0 0 0 0 2 0 1 0 2 2 2 1]
Actual labels: [2 0 1 2 0 1 2 0 0 0 0 0 1 0 1 1 0 1 2 1 2 0 2 1 1 0 0 1 0 2 0 2 0 2 0 1 0
 0 0 1 1 1 0 0 1 0 2 0 0 2 2 2 1 2 0 2 2 2 2 0 1 2 2 0 0 0 2 2 0 1 1 2 0 1
 2 0 0 1 1 1 2 1 0 1 2 1 0 0 0 2 1 1 2 0 2 2 2 2 1 1 1 2 1 0 0 0 0 0 1 0 1
 1 0 0 1 0 2 2 0 2 0 0 0 0 1 1 1 0 2 1 1 0 2 0 2 0 2 2 2 1 1 2 2 2 2 0 2 0
 0 2 0 2 0 1 2 0 2 0 2 1 2 2 2 1 0 0 0 1 0 1 2 1 0 0 2 0 1 1 2 1 2 2 1 0 0
 0 2 0 1 0 0 0 1 0 2 0 0 0 2 0 0 1 0 0 1 0 0 2 1 0 0 0 1 0 2 0 0 0 2 0 1 2
 0 1 1 0 0 0 2 1 2 1 2 1 2 0 1 0 2 0 0 1 2 0 1 1 0 2 0 0 1 0 2 0 2 2 2 0 2
 0 0 0 0 0 2 2 0 0 0 1 1 1 0 0 2 0 2 0 0 2 2 2 0 0 2 2 2 0 0 1 2 0 2 0 0 2
 1 0 2 0 1 1 1 2 2 1 0 0 0 2 0 1 0 2 2 0 0 0 0 2 0 1 0 2 2 2 1]

In [7]:
# Export the trained KNN model to a file
save_path = 'C:/Users/User/Desktop/yolofall/knn_model.pkl'
joblib.dump(knn, save_path)

['C:/Users/User/Desktop/yolofall/knn_model.pkl']